### ISSUE TITLE
关于参考文献

### ISSUE THREAD

**Issue by hushidong** [ElunDai/gdutthesis#1]
我看到todo里面有两点与参考文献有关

* 生成的参考文献中\url字体设置为
Times New Roman
* BUG: \MakeUppercase更改后若恢复原始内容则参考文献四个字无法加入目录的神奇问题

第一点问题是什么现象？
出来的不是Times New Roman?

第二点是出于什么目的？要实现什么
通常不太需要去转mkuppercase命令，因为有其它命令可以用的。

**Comment by hushidong** [comment]
关于第一点 
如果默认设置不行，那么加一条命令
`\urlstyle{same}`

**Comment by hushidong** [comment]
关于第二点
因为还不知道你的需求，所以暂无法提供有效方案

**Comment by ElunDai** [comment]
> 我看到todo里面有两点与参考文献有关
> 
> * 生成的参考文献中\url字体设置为
>   Times New Roman
> * BUG: \MakeUppercase更改后若恢复原始内容则参考文献四个字无法加入目录的神奇问题
> 
> 第一点问题是什么现象？
> 出来的不是Times New Roman?
> 
> 第二点是出于什么目的？要实现什么
> 通常不太需要去转mkuppercase命令，因为有其它命令可以用的。

感谢您的关注！

由于我校要求的参考文献要求的是gb7714-87，要求英文作者名小写。最开始使用让\MakeUppercase失效的方法来实现。现在通过认真阅读您项目的文档发现最新版的biblatex-gb7714-2015已经支持gbnamefmt选项来设置了。 [acdf83c](https://github.com/ElunDai/gdutthesis/commit/acdf83c94466a563be111ea98771666fe5429b05)

在\url字体设置上已经用您的建议进行修改，非常奏效。 [92698da](https://github.com/ElunDai/gdutthesis/commit/92698da959fa50616545fd5b817fc2f19713fedd)
