### ISSUE TITLE
请问毕业论文中的引用怎么使用？

### ISSUE THREAD

**Issue by YorkPeng** [ElunDai/gdutthesis#2]
我已经导出了我的bib文件，并且在configuration.cfg文件中修改了文件位置。在论文中使用\cite{}引用后不出现引用页

**Comment by YorkPeng** [comment]
已经自行解决

**Comment by ElunDai** [comment]
感谢你对本LaTex模板的支持。编译引用页需要编译三次才会出现，虽然我在makefile里面做了改进但是偶尔还是会失败。如果你找到了好方法欢迎将改动合入本项目。(另外，在论文检查时不同的老师会有一些细节上的区别，可能需要自己加一些适配或者直接在Abrocat PDF编辑器上改)
