### ISSUE TITLE
pdf的查重问题~

### ISSUE THREAD

**Issue by ldylab** [ElunDai/gdutthesis#5]
师兄您好，非常非常感谢您的LaTex模板！请问一下您的毕业论文当时在查重过程中，会因为是LaTex的pdf（而非学校给的word格式）而遇到什么问题吗？谢谢您啦！

**Comment by ElunDai** [comment]
当时好像没怎么困扰我，也记不清了。但可以提供几个解决办法：
1. 初次查重可以用pandoc等转档工具将pdf转换成word。
2. 再次查重可以只根据重点段落复制粘贴纯文本到查重框内，可以把多个重点段落都复制进去。
另外补充几点小常识：学校送的查重次数一般是够用的，既然是送的那肯定要全文查重。有些部分如目录可不参与查重，具体看规定。自己查的查重率最好压低一些，与红线保持安全距离。
祝毕业快乐！

**Comment by ldylab** [comment]
好的谢谢师兄！！
