### ISSUE TITLE
Make编译项目的时候PDF首页多了一行figures/

### ISSUE THREAD

**Issue by CY015** [ElunDai/gdutthesis#6]
师兄你好，在**windows**环境下在vscode编译的时候，遇到了一些错误。
第一页会多出来一行字**figures/**(graphicspath括号中的内容，而不是具体图片)，第二页开始才是论文（论文题目，个人信息那些信息）。检查编译log的时候，报错是在**configuration.cfg**第34行，图片路径处 **\graphicspath{{figures/}} % the figures directory**报错，错误提示是**Undefined control sequence \graphicspath**和**Missing \being{document}**。有几个问题想问一下：
1. 这一行是作论文的封面使用的吗？（个人猜测因为在第一页的原因？）如果是作封面，为什么在**figures/**后填写具体文件名它不显示对应的图片呢？（也许是我的LaTeX语法不过关的原因？）
2. 目录和参考文献也没有编译出来

**Comment by CY015** [comment]
感觉还是得在Linux下进行好点，Windows编译会有些问题

**Comment by ElunDai** [comment]
指定`\graphicspath{{figures/}}`只是把图片放在figures/目录里，为了使用\includegraphics的时候不用每次都加figures前缀。
手头上没环境验证，不过可以参考 #7 的解决方式直接删掉graphicspath这行试试。

目录和参考文献是需要重复构建几次才会有的，“生成$(OUTDIR)/$(THESIS).bbl参考文献”和“修正目录”这个打印输出就是重复构建的过程。我在Makefile里写了这个顺序依赖，如果抽风了出不来的话可以试试make compulsory清除标记再make。

**Comment by CY015** [comment]
> 

谢谢师兄回复，这些问题和同学一起研究后都已经解决了，忘了回来留言 :smile: 。
